llm_proxy:
  name: LLM proxy API
  version: demo 1.0
  description: An API that act as a proxy to multiple language models

user_settings:
  # Example
  # - routing_mode: 
  #   - cost_routing:
  #       enable: false
    
  - model: OpenAI
    api_key_var: OPENAI_API_KEY # .env name for api key 
    max_output_tokens: 256 
    temperature: 0.1 
    models: # input names of models you want to you (see below for all models provided)
      # Only models specified here will be added to routing pool
      - gpt-3.5-turbo-instruct
      - gpt-3.5-turbo-1106
      - gpt-4
      - gpt-4-32k
    # context: "Answer politely"

  - model: Llama2
    temperature: 0.1
    api_key_var: LLAMA2_API_KEY
    max_output_tokens: 256
    models:
      - Llama-2-7b-chat-hf
      - Llama-2-13b-chat-hf
      - Llama-2-70b-chat-hf

  - model: Cohere 
    temperature: 0.1
    api_key_var: COHERE_API_KEY 
    max_output_tokens: 256
    models:
      - command
      - command-light
      - command-nightly
      - command-light-nightly

  - model: Mistral
    temperature: 0.1
    api_key_var: MISTRAL_API_KEY
    max_output_tokens: 256
    models:
      - Mistral-7B-v0.1
      - Mistral-7B-Instruct-v0.1

  - model: VertexAI 
    temperature: 0.1
    project_id_var: GOOGLE_PROJECT_ID 
    max_output_tokens: 256 
    models:
      - text-bison
      # Currently not working
      # - chat-bison