llm_proxy:
  name: LLM proxy API
  version: demo 1.0
  description: An API that act as a proxy to multiple language models

user_settings:
  # Example
  # - routing_mode: 
  #   - cost_routing:
  #       enable: false
    
  - model: OpenAI
    api_key_var: OPENAI_API_KEY # .env name for api key 
    max_output_tokens: 256 
    temperature: 0.1 
    models: # input names of models you want to you (see below for all models provided)
      # Only models specified here will be added to routing pool
      - gpt-3.5-turbo-instruct
      - gpt-3.5-turbo-1106
      - gpt-4
      - gpt-4-32k
    # context: "Answer politely"

  - model: Llama2
    temperature: 0.1
    api_key_var: LLAMA2_API_KEY
    max_output_tokens: 256
    models:
      - Llama-2-7b-chat-hf
      - Llama-2-13b-chat-hf
      - Llama-2-70b-chat-hf

  - model: Cohere 
    temperature: 0.1
    api_key_var: COHERE_API_KEY 
    max_output_tokens: 256
    models:
      - command
      - command-light
      - command-nightly
      - command-light-nightly

  - model: Mistral
    temperature: 0.1
    api_key_var: MISTRAL_API_KEY
    max_output_tokens: 256
    models:
      - Mistral-7B-v0.1
      - Mistral-7B-Instruct-v0.1

  - model: VertexAI 
    temperature: 0.1
    project_id_var: GOOGLE_PROJECT_ID 
    max_output_tokens: 256 
    models:
      - text-bison
      # Currently not working
      # - chat-bison

available_models:
  - name: OpenAI
    class: llmproxy.models.openai.OpenAI
    models:
      - name: gpt-3.5-turbo-1106
        cost_per_token_input: 0.0000010
        cost_per_token_output: 0.0000020
        categories:
          Code Generation Task: 2
          Text Generation Task: 1
          Translation and Multilingual Applications Task: 2
          Natural Language Processing Task: 1
          Conversational AI Task: 1
          Educational Applications Task: 2
          Healthcare and Medical Task: 3
          Legal Task: 3
          Financial Task: 3
          Content Recommendation Task: 2
        average_rank: 2.0
      - name: gpt-3.5-turbo-instruct
        cost_per_token_input: 0.0000015
        cost_per_token_output: 0.0000020
        categories:
          Code Generation Task: 2
          Text Generation Task: 1
          Translation and Multilingual Applications Task: 2
          Natural Language Processing Task: 1
          Conversational AI Task: 1
          Educational Applications Task: 2
          Healthcare and Medical Task: 3
          Legal Task: 3
          Financial Task: 3
          Content Recommendation Task: 2
        average_rank: 2.0
      - name: gpt-4
        cost_per_token_input: 0.00003
        cost_per_token_output: 0.00006
        categories:
          Code Generation Task: 1
          Text Generation Task: 1
          Translation and Multilingual Applications Task: 1
          Natural Language Processing Task: 1
          Conversational AI Task: 1
          Educational Applications Task: 1
          Healthcare and Medical Task: 2
          Legal Task: 2
          Financial Task: 2
          Content Recommendation Task: 1
        average_rank: 1.1
      - name: gpt-4-32k
        cost_per_token_input: 0.00006
        cost_per_token_output: 0.00012
        categories:
          Code Generation Task: 1
          Text Generation Task: 1
          Translation and Multilingual Applications Task: 1
          Natural Language Processing Task: 1
          Conversational AI Task: 1
          Educational Applications Task: 1
          Healthcare and Medical Task: 2
          Legal Task: 2
          Financial Task: 2
          Content Recommendation Task: 1
        average_rank: 1.1

  - name: Llama2
    class: llmproxy.models.llama2.Llama2
    models:
      - name: Llama-2-7b-chat-hf
        cost_per_hour: 0.06
        categories:
          Code Generation Task: 2
          Text Generation Task: 1
          Translation and Multilingual Applications Task: 2
          Natural Language Processing Task: 1
          Conversational AI Task: 1
          Educational Applications Task: 2
          Healthcare and Medical Task: 3
          Legal Task: 3
          Financial Task: 3
          Content Recommendation Task: 2
        average_rank: 2.0
      - name: Llama-2-13b-chat-hf
        cost_per_hour: 0.06
        categories:
          Code Generation Task: 1
          Text Generation Task: 1
          Translation and Multilingual Applications Task: 1
          Natural Language Processing Task: 1
          Conversational AI Task: 1
          Educational Applications Task: 1
          Healthcare and Medical Task: 2
          Legal Task: 2
          Financial Task: 2
          Content Recommendation Task: 1
        average_rank: 1.1
      - name: Llama-2-70b-chat-hf
        cost_per_hour: 0.06
        categories:
          Code Generation Task: 1
          Text Generation Task: 1
          Translation and Multilingual Applications Task: 1
          Natural Language Processing Task: 1
          Conversational AI Task: 1
          Educational Applications Task: 1
          Healthcare and Medical Task: 1
          Legal Task: 1
          Financial Task: 1
          Content Recommendation Task: 1
        average_rank: 1.0

  - name: Mistral
    class: llmproxy.models.mistral.Mistral
    models:
      - name: Mistral-7B-v0.1
        cost_per_hour: 0.06
        categories:
          Code Generation Task: 2
          Text Generation Task: 1
          Translation and Multilingual Applications Task: 2
          Natural Language Processing Task: 1
          Conversational AI Task: 1
          Educational Applications Task: 2
          Healthcare and Medical Task: 3
          Legal Task: 3
          Financial Task: 3
          Content Recommendation Task: 2
        average_rank: 2.0
      - name: Mistral-7B-Instruct-v0.1
        cost_per_hour: 0.06
        categories:
          Code Generation Task: 2
          Text Generation Task: 1
          Translation and Multilingual Applications Task: 2
          Natural Language Processing Task: 1
          Conversational AI Task: 1
          Educational Applications Task: 2
          Healthcare and Medical Task: 3
          Legal Task: 3
          Financial Task: 3
          Content Recommendation Task: 2
        average_rank: 2.0

  - name: Cohere
    class: llmproxy.models.cohere.Cohere
    models:
      - name: command
        cost_per_token_input: 0.0000015
        cost_per_token_output: 0.000002
        categories:
          Code Generation Task: 2
          Text Generation Task: 1
          Translation and Multilingual Applications Task: 2
          Natural Language Processing Task: 1
          Conversational AI Task: 1
          Educational Applications Task: 2
          Healthcare and Medical Task: 3
          Legal Task: 3
          Financial Task: 3
          Content Recommendation Task: 2
        average_rank: 2.0
      - name: command-light
        cost_per_token_input: 0.0000015
        cost_per_token_output: 0.000002
        categories:
          Code Generation Task: 3
          Text Generation Task: 2
          Translation and Multilingual Applications Task: 3
          Natural Language Processing Task: 2
          Conversational AI Task: 2
          Educational Applications Task: 3
          Healthcare and Medical Task: 4
          Legal Task: 4
          Financial Task: 4
          Content Recommendation Task: 3
        average_rank: 3.0
      - name: command-nightly
        cost_per_token_input: 0.0000015
        cost_per_token_output: 0.000002
        categories:
          Code Generation Task: 2
          Text Generation Task: 1
          Translation and Multilingual Applications Task: 2
          Natural Language Processing Task: 1
          Conversational AI Task: 1
          Educational Applications Task: 2
          Healthcare and Medical Task: 3
          Legal Task: 3
          Financial Task: 3
          Content Recommendation Task: 2
        average_rank: 2.0
      - name: command-light-nightly
        cost_per_token_input: 0.0000015
        cost_per_token_output: 0.000002
        categories:
          Code Generation Task: 3
          Text Generation Task: 2
          Translation and Multilingual Applications Task: 3
          Natural Language Processing Task: 2
          Conversational AI Task: 2
          Educational Applications Task: 3
          Healthcare and Medical Task: 4
          Legal Task: 4
          Financial Task: 4
          Content Recommendation Task: 3
        average_rank: 3.0

  - name: Vertexai
    class: llmproxy.models.vertexai.VertexAI
    models:
      - name: text-bison
        cost_per_token_input: 0.0000015
        cost_per_token_output: 0.000002
        categories:
          Code Generation Task: 1
          Text Generation Task: 1
          Translation and Multilingual Applications Task: 1
          Natural Language Processing Task: 1
          Conversational AI Task: 2
          Educational Applications Task: 1
          Healthcare and Medical Task: 2
          Legal Task: 2
          Financial Task: 2
          Content Recommendation Task: 1
        average_rank: 1.4

      # Currently not working
      # - name: chat-bison-32k
      #   cost_per_token_input: 0.000002
      #   cost_per_token_output: 0.000002
