available_models:
  - name: OpenAI
    class: llmproxy.provider.openai.chatgpt.OpenAI
    max-output-tokens: 50
    models:
      - name: gpt-3.5-turbo-1106
        cost_per_token_input: 0.0000010
        cost_per_token_output: 0.0000020
      - name: gpt-3.5-turbo-instruct
        cost_per_token_input: 0.0000015
        cost_per_token_output: 0.0000020
      - name: gpt-4
        cost_per_token_input: 0.00003
        cost_per_token_output: 0.00006
      - name: gpt-4-32k
        cost_per_token_input: 0.00006
        cost_per_token_output: 0.00012

  - name: Llama2
    class: llmproxy.provider.huggingface.llama2.Llama2
    max-output-tokens: 50
    models:
      - name: Llama-2-7b-chat-hf
        cost_per_token_input: 0.00000005
        cost_per_token_output: 0.00000025
      - name: Llama-2-7b-chat
        cost_per_token_input: 0.00000005
        cost_per_token_output: 0.00000025
      - name: Llama-2-7b-hf
        cost_per_token_input: 0.00000005
        cost_per_token_output: 0.00000025
      - name: Llama-2-7b
        cost_per_token_input: 0.00000005
        cost_per_token_output: 0.00000025
      - name: Llama-2-13b-chat-hf
        cost_per_token_input: 0.0000001
        cost_per_token_output: 0.0000005
      - name: Llama-2-13b-chat
        cost_per_token_input: 0.0000001
        cost_per_token_output: 0.0000005
      - name: Llama-2-13b-hf
        cost_per_token_input: 0.0000001
        cost_per_token_output: 0.0000005
      - name: Llama-2-13b
        cost_per_token_input: 0.0000001
        cost_per_token_output: 0.0000005
      - name: Llama-2-70b-chat-hf
        cost_per_token_input: 0.00000065
        cost_per_token_output: 0.00000275
      - name: Llama-2-70b-chat
        cost_per_token_input: 0.00000065
        cost_per_token_output: 0.00000275
      - name: Llama-2-70b-hf
        cost_per_token_input: 0.00000065
        cost_per_token_output: 0.00000275
      - name: Llama-2-70b
        cost_per_token_input: 0.00000065
        cost_per_token_output: 0.00000275

  - name: Mistral
    class: llmproxy.provider.huggingface.mistral.Mistral
    max-output-tokens: 50
    models:
      - name: Mistral-7B-v0.1
        cost_per_token_input: 0.00000005
        cost_per_token_output: 0.00000025
      - name: Mistral-7B-Instruct-v0.2
        cost_per_token_input: 0.00000005
        cost_per_token_output: 0.00000025
      - name: Mistral-8x7B-Instruct-v0.1
        cost_per_token_input: 0.0000003
        cost_per_token_output: 0.000001

  - name: Cohere
    class: llmproxy.provider.cohere.cohere.Cohere
    max-output-tokens: 50
    models:
      - name: command
        cost_per_token_input: 0.0000015
        cost_per_token_output: 0.000002
      - name: command-light
        cost_per_token_input: 0.0000015
        cost_per_token_output: 0.000002
      - name: command-nightly
        cost_per_token_input: 0.0000015
        cost_per_token_output: 0.000002
      - name: command-light-nightly
        cost_per_token_input: 0.0000015
        cost_per_token_output: 0.000002

  - name: Vertexai
    class: llmproxy.provider.google.vertexai.VertexAI
    max-output-tokens: 50
    models:
      - name: text-bison
        cost_per_token_input: 0.0000005
        cost_per_token_output: 0.0000005
      # Currently not working
      # - name: chat-bison-32k
      #   cost_per_token_input: 0.000002
      #   cost_per_token_output: 0.000002
