name: lint

on: push

jobs:
    
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run black formatter
        uses: psf/black@stable
        with:
          options: "--check --diff --color"
          src: "./llmproxy"
          version: "~= 22.0"
            
