name: scan for secrets

on: push

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update pre-commit hooks
        run: |
          pre-commit autoupdate

      - name: Secret Scanner
        uses: secret-scanner/action@0.0.2
        with:
          detect-secrets-version: '1.2.0'

