name: scan for secrets

on: push

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Secret Scanner
        uses: secret-scanner/action@0.0.2
