name: Unused Imports

on: push

jobs:
  unused-imports:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: creyD/autoflake_action@master
      with:
        options: --remove-all-unused-imports --recursive --in-place --exclude=__init__.py
