name: Unused Imports

on: push

jobs:
  lint-and-clean:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1.3.4
      with:
        version: 1.6.1
        virtualenvs-create: false

    - name: Remove unused imports with autoflake and check with flake8
      run: |
        poetry run autoflake --remove-all-unused-imports --recursive --in-place --exclude=__init__.py .

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Remove unused imports'
        branch: ${{ github.head_ref }}
        file_pattern: '*.py'
